#Delivery Pipeline for our clusters

apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: gitops
description: main application pipeline
serialPipeline:
  stages:
  - targetId: qsdev
  - targetId: qsprod
---

#Our 1st Cluster TARGET
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: qsdev
description: development cluster
gke:
 cluster:  projects/my-first-project-17342/locations/asia-east1-a/clusters/cluster1
executionConfigs:
- defaultPool:
    serviceAccount: gke-sa@my-first-project-17342.iam.gserviceaccount.com
  usages:
  - RENDER 
  - DEPLOY   
---
#Our 2st Cluster TARGET

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: qsprod
description: production cluster
requireApproval: true
gke:
 cluster:  projects/my-first-project-17342//locations/us-west1-a/clusters/cluster-prod
executionConfigs:
- defaultPool:
    serviceAccount: gke-sa@my-first-project-17342.iam.gserviceaccount.com
  usages:
  - RENDER 
  - DEPLOY
